### ISSUE TITLE
Update table data

### ISSUE THREAD

**Issue by tomerb15** [Shailu4u/AngularJS-Nested-Datatable#1]
Hey,
How can i replace the current table's data with a new data? (e.g: a change between 2 JSON files)

**Comment by Shailu4u** [comment]
You can always add new data in format of data,json (should have sameobject modal) and bind it to data attribute of ng-nested-datatable directive. If you want to change data to some inner level of tables, then you change data in that inner level alone in data.json.

**Comment by tomerb15** [comment]
Thanks for the answer. My current need is to replace the entire table data including all levels.
I have a select dropdown and every time the user selects an option, I'm fetching new jason that should replace the entire table.
Is there a quick way of doing so?

**Comment by Shailu4u** [comment]
That new json should be binded to data attribute of ng-nested-datatable
directive..

On 1 October 2015 at 13:59, tomerb15 notifications@github.com wrote:

> Thanks for the answer. My current need is to replace the entire table data
> including all levels.
> I have a select dropdown and every time the user selects an option, I'm
> fetching new jason that should replace the entire table.
> Is there a quick way of doing so?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Shailu4u/AngularJS-Nested-Datatable/issues/1#issuecomment-144654583
> .

## 

Thanks & Regards,
shailendra
"SAVE PAPER - THINK BEFORE YOU PRINT"
"Great minds discuss ideas. Average minds discuss events. Small minds
discuss people."

**Comment by tomerb15** [comment]
This is my use of the directive:
<ng-nested-datatable   
    data="tableData"
    outer-table-config="outerDefaults"
    inner-table-config="innerDefaults">
</ng-nested-datatable>

tableData is the $scope model that "data" is binded to, but when i change the data in the modal, the change is not reflected in the table.

sorry for the few details i shared before, i hope that now you better understand my problem.

**Comment by tomerb15** [comment]
Hey Shailu, here is my directive:
    `<ng-nested-datatable   data="changableData"`
   `outer-table-config="outerDefaults"`
   `inner-table-config="innerDefaults">`
   `</ng-nested-datatable>`

`changableData` is a scope variable that is defined in the controller of the page.

i also have the following dropdown:
`<select chosen`
  `class="chosen-select"`
      `ng-change="changableDataReplace()">`
       `<option><option>`
`</select>`

`changableDataReplace()` is defined inside the controller like this:
`$scope.changableDataReplace = function(){`
`$scope.changableData = { new jason string here }`
`}`

The view is not changed when this code is executed although i can see in the debugger that `changableData` was changed with new data.

I would really appreciate your kind help.

Thanks!

**Comment by Shailu4u** [comment]
One way solution is to use ng-if="showTable" on directive. Just change the value of showTable to 'false' initially, and change to 'true' before updating new data. So that directive will be removed from DOM initially and added to DOM with new data.
Please find updated code in controller app.js

**Comment by tomerb15** [comment]
Thank you very much, it works great now with Json files!
However, if my data comes from a variable that i change not by using DataService, it seems to not update again.
for example:

```
       $scope.showTable = false;
       var data1 = {
            "level": {
                "Headings": ["col1", "col2", "col3", "col4"],
                "TableRows": [
                    {
                        "data": ["table11", "100000", "150000", "569"]
                    }
                ]
            }
        };
        var data2 = {
            "level": {
                "Headings": ["data2", "data2", "data2", "data2"],
                "TableRows": [

                    {
                        "data": ["data2", "data2", "data2", "data2"]
                    }
                ]
            }
        };
        $scope.showTable = false;
        if($scope.someBoolean){
            $scope.someBoolean = false;
            $scope.showTable = true;
            $scope.tableData = data1;
        }else{
            $scope.someBoolean = true;
            $scope.showTable = true;
            $scope.tableData = data2;
        }
```

**Comment by Shailu4u** [comment]
You can listen to changes by using $scope.$watch and before/ after updating with new data just make changes to $scope.showTable to false/true respectively.

**Comment by tomerb15** [comment]
will do! :+1: 
have you meant $scope.showTable instead of $scope.showdata?

**Comment by Shailu4u** [comment]
Yes its $scope.showTable...updated comment
